sudo:  required
services: 
  - docker

before_install: 
  - gem install bundler
  - docker build -t kblan017/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kblan017/docker-react npm run test -- --coverage